import uuid
import secrets
import hashlib
import logging
from typing import Optional, List
from fastapi import APIRouter, Depends, status, Query, Body
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, delete

from app.core.database import get_db
from app.api.dependencies.auth import get_current_user
from app.database.models import User, Repository, Organization, OrganizationMember, APIKey, Webhook, AuditLog
from app.core.exceptions import NotFoundError

router = APIRouter(prefix="/enterprise", tags=["Enterprise Identity & Extensibility"])
logger = logging.getLogger("repolens.routes.enterprise")


# 1. ORGANIZATIONS & TEAMS
@router.post("/organizations", status_code=status.HTTP_201_CREATED)
async def create_organization(
    name: str = Body(..., embed=True),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Create a new enterprise tenant organization and write audit trails"""
    org = Organization(name=name)
    db.add(org)
    await db.commit()
    await db.refresh(org)

    # Make creator owner
    member = OrganizationMember(
        organization_id=org.id,
        user_id=current_user.id,
        role="owner"
    )
    db.add(member)

    # Log audit event
    audit = AuditLog(
        user_id=current_user.id,
        action="organization.create",
        metadata_json={"organization_id": str(org.id), "org_name": name}
    )
    db.add(audit)
    await db.commit()

    return {
        "id": str(org.id),
        "name": org.name,
        "created_at": org.created_at
    }


@router.get("/organizations", status_code=status.HTTP_200_OK)
async def list_organizations(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List organizations the user is a member of"""
    query = (
        select(Organization)
        .join(OrganizationMember, OrganizationMember.organization_id == Organization.id)
        .where(OrganizationMember.user_id == current_user.id)
    )
    res = await db.execute(query)
    orgs = []
    for org in res.scalars().all():
        orgs.append({
            "id": str(org.id),
            "name": org.name,
            "created_at": org.created_at
        })
    return orgs


# 2. PUBLIC API KEYS
@router.post("/api-keys", status_code=status.HTTP_201_CREATED)
async def generate_api_key(
    name: str = Body(..., embed=True),
    organization_id: Optional[uuid.UUID] = Body(None, embed=True),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Generate a hashed public API key and return the raw token once"""
    raw_token = "rl_" + secrets.token_hex(24)
    hashed_key = hashlib.sha256(raw_token.encode()).hexdigest()

    key_record = APIKey(
        user_id=current_user.id,
        organization_id=organization_id,
        key_hash=hashed_key,
        name=name
    )
    db.add(key_record)

    # Log audit
    audit = AuditLog(
        user_id=current_user.id,
        action="api_key.create",
        metadata_json={"key_name": name}
    )
    db.add(audit)
    await db.commit()

    return {
        "id": str(key_record.id),
        "name": key_record.name,
        "token": raw_token, # ONLY displayed once upon creation
        "created_at": key_record.created_at
    }


@router.get("/api-keys", status_code=status.HTTP_200_OK)
async def list_api_keys(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List API keys generated by the current user"""
    query = select(APIKey).where(APIKey.user_id == current_user.id)
    res = await db.execute(query)
    keys = []
    for k in res.scalars().all():
        keys.append({
            "id": str(k.id),
            "name": k.name,
            "created_at": k.created_at
        })
    return keys


@router.delete("/api-keys/{id}", status_code=status.HTTP_204_NO_CONTENT)
async def revoke_api_key(
    id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Revoke and delete a public API Key"""
    query = select(APIKey).where(APIKey.id == id, APIKey.user_id == current_user.id)
    res = await db.execute(query)
    key_rec = res.scalar_one_or_none()
    if not key_rec:
        raise NotFoundError("APIKey")

    # Log audit
    audit = AuditLog(
        user_id=current_user.id,
        action="api_key.revoke",
        metadata_json={"key_name": key_rec.name}
    )
    db.add(audit)

    await db.execute(delete(APIKey).where(APIKey.id == id))
    await db.commit()


# 3. WEBHOOKS
@router.post("/webhooks", status_code=status.HTTP_201_CREATED)
async def register_webhook(
    repository_id: uuid.UUID = Body(...),
    target_url: str = Body(...),
    secret_token: str = Body(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Register an outbound webhook listener for repository events"""
    # Verify repository ownership
    repo_query = await db.execute(
        select(Repository).where(
            Repository.id == repository_id,
            Repository.user_id == current_user.id
        )
    )
    repo = repo_query.scalar_one_or_none()
    if not repo:
        raise NotFoundError("Repository")

    webhook = Webhook(
        repository_id=repository_id,
        target_url=target_url,
        secret_token=secret_token,
        is_active=True
    )
    db.add(webhook)

    # Log audit
    audit = AuditLog(
        user_id=current_user.id,
        action="webhook.register",
        metadata_json={"repository_id": str(repository_id), "target_url": target_url}
    )
    db.add(audit)
    await db.commit()
    await db.refresh(webhook)

    return {
        "id": str(webhook.id),
        "target_url": webhook.target_url,
        "is_active": webhook.is_active,
        "created_at": webhook.created_at
    }


@router.get("/webhooks", status_code=status.HTTP_200_OK)
async def list_webhooks(
    repository_id: uuid.UUID = Query(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List webhooks configured for a repository"""
    # Verify owner
    repo_query = await db.execute(
        select(Repository).where(
            Repository.id == repository_id,
            Repository.user_id == current_user.id
        )
    )
    repo = repo_query.scalar_one_or_none()
    if not repo:
        raise NotFoundError("Repository")

    query = select(Webhook).where(Webhook.repository_id == repository_id)
    res = await db.execute(query)
    webhooks = []
    for wh in res.scalars().all():
        webhooks.append({
            "id": str(wh.id),
            "target_url": wh.target_url,
            "is_active": wh.is_active,
            "created_at": wh.created_at
        })
    return webhooks


# 4. AUDIT TRAIL LOGS
@router.get("/audit", status_code=status.HTTP_200_OK)
async def list_audit_logs(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Fetch security compliance audit trails log"""
    query = select(AuditLog).where(AuditLog.user_id == current_user.id).order_by(AuditLog.created_at.desc())
    res = await db.execute(query)
    logs = []
    for l in res.scalars().all():
        logs.append({
            "id": str(l.id),
            "action": l.action,
            "metadata": l.metadata_json,
            "created_at": l.created_at
        })
    return logs
