import abc
from typing import AsyncGenerator


class LLMProviderInterface(abc.ABC):
    @abc.abstractmethod
    async def generate_stream(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 2048
    ) -> AsyncGenerator[str, None]:
        """Asynchronously stream chunks of text tokens generated by the LLM model"""
        yield ""

    @abc.abstractmethod
    async def generate_text(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 2048
    ) -> str:
        """Asynchronously retrieve the entire text response generated by the LLM model"""
        pass
